language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install coveralls

script:
  - python3 -m pytest --rootdir=tests

after_success:
  - coverage run --source=pyrunner_api -m pytest tests/
  - coveralls