language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - python3 -m pip install .
  - python3 -m pip install coveralls coverage

script:
  - python3 -m pytest --rootdir=tests

after_success:
  - python3 -m coverage run --source=pyrunner -m pytest tests/
  - coveralls